name: gsequencer-3 # you probably want to 'snapcraft register <name>'
version: '3.19.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Advanced Gtk+ Sequencer # 79 char long summary
description: |
  GSequencer is intended to be use for music composition. It features
  notation, automation and wave form editor. Supporting LADSPA, DSSI
  and LV2 plugins.
icon: snap/ags.png

base: core
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
#passthrough:
#  confinement: next-generation # use 'strict' once you have the right plugs and slots

parts:
  gsequencer:
    source: http://download-mirror.savannah.gnu.org/releases/gsequencer/3.19.x/gsequencer-3.19.0.tar.gz # See 'snapcraft plugins'
    plugin: autotools
    build-packages: [wget,dblatex,gstreamer1.0-plugins-base,gstreamer1.0-plugins-good,gstreamer1.0-plugins-bad,libgstreamer1.0-dev,libgstreamer-plugins-base1.0-dev,libgtk-3-dev,libinstpatch-dev,libsndfile-dev,libsamplerate-dev,libsoup2.4-dev,libxml2-dev,libpoppler-glib-dev,gobject-introspection,libgmp-dev,ladspa-sdk,dssi-dev,lv2-dev,fftw3-dev,libasound2-dev,libjack-jackd2-dev,libpulse-dev,uuid-dev,libcunit1-dev,docbook-xsl,docbook-xml,gtk-doc-tools,xsltproc]
    stage-packages: [libatk-bridge2.0-0,libatspi2.0-0,libbrotli1,libcairo-gobject2,libdrm2,libegl1,libenchant1c2a,libepoxy0,libfftw3-double3,libgbm1,libgl1,libglvnd0,libglx0,libgstreamer-gl1.0-0,gstreamer1.0-plugins-base,gstreamer1.0-plugins-good,libgstreamer-plugins-base1.0-0,libgstreamer1.0-0,libgtk-3-0,libgudev-1.0-0,libharfbuzz-icu0,libhyphen0,libinstpatch-1.0-0,libjavascriptcoregtk-4.0-18,libnotify4,liborc-0.4-0,libsecret-1-0,libsoup2.4-1,libpoppler-glib8,libwayland-client0,libwayland-cursor0,libwayland-egl1,libwayland-server0,libwebp6,libwebpdemux2,libwoff1,libx11-xcb1,libxkbcommon0,libxslt1.1,ubuntustudio-audio-plugins,cmt,xsynth-dssi,calf-plugins,invada-studio-plugins-lv2,mda-lv2,swh-plugins,hydrogen-drumkits,fluid-soundfont-gm,fluid-soundfont-gs]
    override-build: |
      ./configure HTMLHELP_XSL=/usr/share/xml/docbook/stylesheet/docbook-xsl/htmlhelp/htmlhelp.xsl --prefix=/usr --libdir=/usr/lib/$SNAPCRAFT_ARCH_TRIPLET --enable-public-libgsequencer --disable-introspection
      make -j $SNAPCRAFT_PARALLEL_BUILD_COUNT
      make -j1 pdf
      DESTDIR=$SNAPCRAFT_PART_INSTALL make -j1 install
      DESTDIR=$SNAPCRAFT_PART_INSTALL make -j1 install-pdf-mkdir
      DESTDIR=$SNAPCRAFT_PART_INSTALL make -j1 install-pdf
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/include
    override-pull: |
      snapcraftctl pull
      wget http://xn--krhemann-1za.com/snap/configure-ac.patch
      wget http://xn--krhemann-1za.com/snap/file-chooser-shortcuts.patch
      patch -p0 < configure-ac.patch
      patch -p0 < file-chooser-shortcuts.patch
      autoreconf -fi

apps:
  gsequencer:
    command: usr/bin/gsequencer
    extensions: [gnome]
    desktop: usr/share/applications/gsequencer.desktop
    environment:
      XDG_DATA_DIRS: $SNAP/usr/share:$XDG_DATA_DIRS
      LADSPA_PATH: $SNAP/usr/lib/ladspa
      DSSI_PATH: $SNAP/usr/lib/dssi
      LV2_PATH: $SNAP/usr/lib/lv2
      AGS_SNAP_PATH: $SNAP
      AGS_ANIMATION_FILENAME: $SNAP/usr/share/gsequencer/images/gsequencer-800x450.png
      AGS_LOGO_FILENAME: $SNAP/usr/share/gsequencer/images/ags.png
      AGS_CSS_FILENAME: $SNAP/usr/share/gsequencer/styles/ags.css
      AGS_ONLINE_HELP_START_FILENAME: file://$SNAP/usr/share/doc/gsequencer/html/index.html
    plugs:
      - x11
      - wayland
      - desktop
      - alsa
      - pulseaudio
      - gsettings
      - home
      - content
      - openvswitch

plugs:
  icon-themes:
    interface: content
    target: $SNAP/usr/share/icons
    default-provider: gtk-common-themes:icon-themes

#passthrough:
#  layout:
#    /usr/share/sounds:
#      bind: $SNAP/usr/share/sounds
#    /usr/share/hydrogen:
#      bind: $SNAP/usr/share/hydrogen
